orionjoss/mendly

app/controllers/lists_controller.rb, app/controllers/recommendation_lists_controller.rb, app/controllers/recommendations_controller.rb, app/controllers/users_controller.rb, app/views/devise/shared/_flashes.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20230829104111_add_devise_to_users.rb, test/controllers/lists_controller_test.rb, test/controllers/recommendation_lists_controller_test.rb, test/controllers/recommendations_controller_test.rb, test/controllers/users_controller_test.rb
generated all controllers and respective routes
=> generated controllers and routes

Gemfile, Gemfile.lock, db/seeds.rb
Seeeeeeds using faker. Still missing some more.
=> created a bunch of fakers and seeds

Gemfile.lock, app/controllers/lists_controller.rb, app/controllers/recommendations_controller.rb, app/views/layouts/application.html.erb, app/views/lists/new.html.erb, app/views/lists/show.html.erb, app/views/recommendations/new.html.erb, config/routes.rb
lists views: show and edit
delete list button
change home route from chat to home
=> Views lists and recommendations

Gemfile, app/controllers/pages_controller.rb, app/controllers/users_controller.rb, app/views/users/show.html.erb
created users controller and respective view and landing page.html.erb
=> Views pages and users

app/controllers/recommendations_controller.rb, app/views/recommendations/edit.html.erb, app/views/recommendations/show.html.erb
- recommendations working:
- show
- create
- edit, might not be necessary
- delete.
- forms made for edit and new
=> recommendations working: show, create, edit, delete. with forms

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/pages/landing.html.erb, app/views/shared/_navbar.html.erb
organized navbar (still need to fix the dropdown)
inserted navbar
organized alignments in application.html
=> navbar, search bar and yield area defined

app/views/layouts/application.html.erb, app/views/pages/landing.html.erb, app/views/shared/_navbar.html.erb
=> small stuff

app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
general ui
still have to make the filters work
=> Home front end structure

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_index.scss, app/views/recommendations/new.html.erb
front end for edit recommendation and edit lists
=> Add new recommendation frontend

db/seeds.rb
Bug was fixed and added a little bit more intelligence for the better storytelling of our product. 
Please review and merge once checked. There's a bunch of code that's commented out. I will still work on those later.
=> User seed password

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/lists_controller.rb, app/views/layouts/application.html.erb, app/views/lists/show.html.erb, app/views/pages/home.html.erb, app/views/pages/landing.html.erb, app/views/recommendations/show.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
Finished the recommendations page
finished the lists pages
Changed to dark mode
Changes searchbar and navbar
=> Fix recommendation page

app/assets/stylesheets/components/_button.scss, app/views/lists/new.html.erb, app/views/pages/home.html.erb, app/views/recommendations/edit.html.erb, app/views/recommendations/new.html.erb, app/views/recommendations/show.html.erb
styles for new and edit pages for recs and lists
fix add rec to list button at home
=> Fix dropdown recommendation page

app/assets/stylesheets/components/_box.scss, app/controllers/lists_controller.rb, app/controllers/recommendation_lists_controller.rb, app/views/lists/show.html.erb, app/views/pages/home.html.erb, app/views/pages/landing.html.erb, app/views/recommendations/show.html.erb, config/routes.rb
inside a collection:
- add mendly
- new mendly
=> collection fixes.

app/models/chatroom.rb, app/models/message.rb, db/migrate/20230904221635_create_chatrooms.rb, db/migrate/20230904221650_create_messages.rb, db/migrate/20230905003621_modify_chatroom_foreign_key.rb, db/schema.rb, db/seeds.rb, test/models/chatroom_test.rb
While implementing the chat, I had to implement a new model called "Chatrooms" to be able to create the chats. I didn't know how to use the "view" and "chat" on the page, so I followed what was easier for me to accomplish.
=> generated new model for chatroom and changed migration for messages

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/components/_text.scss, app/views/chatrooms/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/splash.html.erb
still stuff to do in the text of the boxes and searchbar
we have to change the thumbnail
=> Chatbot UI

app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_image.scss, app/assets/stylesheets/components/_text.scss, app/views/pages/landing.html.erb
fixes landing page. testimonials incomplete
=> fixes landing page. testimonials incomplete

app/assets/stylesheets/components/_background.scss, app/views/layouts/application.html.erb
=> fix splash page

app/assets/stylesheets/components/_background.scss, app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_navbar.scss, app/views/lists/new.html.erb, app/views/lists/show.html.erb, app/views/pages/home.html.erb, app/views/recommendations/new.html.erb
=> fixes ui and share button

app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_button.scss, app/views/lists/show.html.erb, app/views/recommendations/show.html.erb
new card layout
download button
card line height
=> new card layout and other minor things

app/services/openai_service.rb
We had to change the link from the local database to the remote database. 
We created an if else statement to local x remote db.
=> update db connection string that was breaking LangChain. All good

app/assets/stylesheets/components/_box.scss, app/views/chatrooms/show.html.erb
help button
link query to jorge marques
=> chat fixes

app/views/pages/landing.html.erb, app/views/shared/_navbar.html.erb
testimonials and thumbs
thumb orion
=> thumbnails and testimonials

app/assets/stylesheets/components/_background.scss, app/assets/stylesheets/components/_box.scss, app/views/lists/show.html.erb, app/views/pages/404.html.erb, app/views/recommendations/show.html.erb
drop-down netflix e tal
fix collection chaos
=> drop-down available. fox collection chaos

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_text.scss, app/views/lists/show.html.erb, app/views/pages/landing.html.erb
=> last push???
